### ISSUE TITLE
Not working with recent releases

### ISSUE THREAD

**Issue by unbracketed** [cldellow/datasette-ui-extras#107]
After installing the plugin and starting datasette, I get an error. 

```
datasette --version
datasette, version 1.0a13
```
```
datasette --root test_events.db
Traceback (most recent call last):
  File "/Users/brian/code/exploration/datasette/datasette/.venv/bin/datasette", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/brian/code/exploration/datasette/datasette/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/code/exploration/datasette/datasette/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/brian/code/exploration/datasette/datasette/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/code/exploration/datasette/datasette/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/code/exploration/datasette/datasette/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/code/exploration/datasette/datasette/.venv/lib/python3.12/site-packages/datasette/cli.py", line 96, in wrapped
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/code/exploration/datasette/datasette/.venv/lib/python3.12/site-packages/datasette/cli.py", line 610, in serve
    asyncio.get_event_loop().run_until_complete(ds.invoke_startup())
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/brian/code/exploration/datasette/datasette/.venv/lib/python3.12/site-packages/datasette/app.py", line 545, in invoke_startup
    for hook in pm.hook.startup(datasette=self):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/code/exploration/datasette/datasette/.venv/lib/python3.12/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/code/exploration/datasette/datasette/.venv/lib/python3.12/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/code/exploration/datasette/datasette/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/Users/brian/code/exploration/datasette/datasette/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/code/exploration/datasette/datasette/.venv/lib/python3.12/site-packages/datasette_ui_extras/__init__.py", line 212, in startup
    enable_yolo_facets()
  File "/Users/brian/code/exploration/datasette/datasette/.venv/lib/python3.12/site-packages/datasette_ui_extras/facets.py", line 119, in enable_yolo_facets
    patch_TableView_data()
  File "/Users/brian/code/exploration/datasette/datasette/.venv/lib/python3.12/site-packages/datasette_ui_extras/facets.py", line 67, in patch_TableView_data
    from datasette.views.table import TableView
ImportError: cannot import name 'TableView' from 'datasette.views.table' (/Users/brian/code/exploration/datasette/datasette/.venv/lib/python3.12/site-packages/datasette/views/table.py). Did you mean: 'table_view'
```

**Comment by CharlesNepote** [comment]
Same issue here with `datasette, version 1.0a16`.
